runtime: nodejs18
instance_class: F2
env_variables:
  MONGO_CONNECTION_STRING: 'mongodb+srv://empireone:hXCieVuIw5DvCX7z@serverlessinstance1.ey8tlta.mongodb.net/?retryWrites=true&w=majority'
  MONGODB_DATABASE: 'hrserverless_db'
  JWT_SECRET_KEY: '431dd5dddcde37181d3816f9e604083693b7fc52873db4a8f2b009d51a23937f'
  SALT: '10'
  PORT: '8080'
  API_KEY: 'YOUR_API_KEY'
  CLIENT_ID: 'YOUR_CLIENT_ID'
  CLIENT_SECRET: 'YOUR_CLIENT_SECRET'
  GMAIL_USER_REFRESH_TOKEN: 'YOUR_GMAIL_USER_REFRESH_TOKEN'
  
handlers:
  - url: /api/uploadImage
    script: auto
    secure: always

# Add the following handler to serve the 'uploads' directory as a static resource
- url: /uploads
  static_dir: uploads

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto