runtime: nodejs18
instance_class: F2
env_variables:
  MONGO_CONNECTION_STRING: 'mongodb+srv://empireone:hXCieVuIw5DvCX7z@serverlessinstance1.ey8tlta.mongodb.net/?retryWrites=true&w=majority'
  MONGODB_DATABASE: 'hrserverless_db'
  JWT_SECRET_KEY: '431dd5dddcde37181d3816f9e604083693b7fc52873db4a8f2b009d51a23937f'
  SALT: '10'
  PORT: '8080'
  API_KEY: 'AIzaSyAI1NsFZrRaBSRCtj8TkIxA3Mg-qYFDRzg'
  CLIENT_ID: '699215781260-odsjje0uf982v9uqut3t0uro8qrkbea7.apps.googleusercontent.com'
  CLIENT_SECRET: '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'
  GMAIL_USER_REFRESH_TOKEN: 'ya29.a0AbVbY6P9ok-s2IDSMcWhb0JuV6GSUJKeUn5LS0Z_QXLQSLMLQGI3KWnxmH7JHP74VLSC-OEjSduKx4zXYLYo5NNxHJhDDgYJUWdVrnmFP2mOreC7j6NqKpvIdDoxCOLXdyE2ALXzdaV4Y0_20BOp1kPEd7T0aCgYKAdYSARMSFQFWKvPlTbcIqX80C9fPscH0ll0YaQ0163'
  BUCKET_NAME: 'hrsystem_bucket1'
  GOOGLE_APPLICATION_CREDENTIALS: "src/config/empireone-global-inc-b59f5dc6818c.json"

handlers:
  - url: /api/uploadImage
    script: auto
    secure: always
  - url: /images/(.*\.(png|jpg|jpeg|gif|bmp|webp))$
    secure: always
    static_files: uploads/\1
    upload: uploads/(.*\.(png|jpg|jpeg|gif|bmp|webp))$