[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "https://hrsystem-dev.empireonecontactcenter.com/"

[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "14"

[functions]
  directory = "src"
