[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"

[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "14"

[functions]
  directory = "src"
